# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license
# Builds ultralytics/yolov5:latest image on DockerHub https://hub.docker.com/r/ultralytics/yolov5
# Image is CUDA-optimized for YOLOv5 single/multi-GPU training and inference

# Start FROM DeepStream docker image https://catalog.ngc.nvidia.com/orgs/nvidia/containers/deepstream
# with CUDA 11.6, Ubuntu 20.04, CUDNN 8.3.2, Triton 2.20.0

FROM nvcr.io/nvidia/deepstream:6.1-triton

ENV TRT_VERSION=8.4.1 \
    CUDA_VERSION=11.6.0 \
    NVIDIA_DRIVER_CAPABILITIES=$NVIDIA_DRIVER_CAPABILITIES,video \
    DEBIAN_FRONTEND=noninteractive \
    OMP_NUM_THREADS=1
SHELL ["/bin/bash", "-c"]

# With DeepStream 6.2, the docker containers do not package libraries necessary for certain multimedia
# operations like audio data parsing, CPU decode, and CPU encode. This change could affect processing 
# certain video streams/files like mp4 that include audio track.
# RUN sh /opt/nvidia/deepstream/deepstream/user_additional_install.sh

# Downloads to user config dir
ADD https://ultralytics.com/assets/Arial.ttf https://ultralytics.com/assets/Arial.Unicode.ttf /root/.config/Ultralytics/

# Install linux packages
RUN apt update && \
    TZ=Etc/UTC apt install -y tzdata && \
    apt install --no-install-recommends --yes \
    gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg build-essential libopencv-dev \
    libtool autoconf autogen pkg-config cmake dkms \
    libssl1.1 \
    libgstreamer1.0-0 \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer-plugins-base1.0-dev \
    libgstrtspserver-1.0-0 libjansson4 \
    libyaml-cpp-dev gcc make git python3 python3-dev python3-pip
# RUN alias python=python3

# Install TensorRT
# CUDA version should not be equal 10.2
RUN v="${TRT_VERSION}-1+cuda${CUDA_VERSION%.*}" && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub && \
    apt-get update && \
    apt-get install -y libnvinfer8=${v} libnvonnxparsers8=${v} libnvparsers8=${v} libnvinfer-plugin8=${v} \
        libnvinfer-dev=${v} libnvonnxparsers-dev=${v} libnvparsers-dev=${v} libnvinfer-plugin-dev=${v} \
        python3-libnvinfer=${v} libnvinfer-samples=${v} && \
    cd /usr/src/tensorrt/samples/trtexec && make

# Create working directory
RUN rm -rf /usr/src/app && mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install pip packages
COPY requirements/ /usr/src/app/requirements/
RUN python3 -m pip install --upgrade pip wheel setuptools && \
    pip install --no-cache -r requirements/preinstall.txt && \
    pip install --no-cache -r requirements/install.txt -r requirements/deploy.txt
    # tensorflow tensorflowjs \

# Cleanup
ENV DEBIAN_FRONTEND=teletype


# Usage Examples -------------------------------------------------------------------------------------------------------

# Build and Push
# t=ultralytics/yolov5:latest && sudo docker build -f utils/docker/Dockerfile -t $t . && sudo docker push $t

# Pull and Run
# t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t

# Pull and Run with local directory access
# t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all -v "$(pwd)"/datasets:/usr/src/datasets $t

# Kill all
# sudo docker kill $(sudo docker ps -q)

# Kill all image-based
# sudo docker kill $(sudo docker ps -qa --filter ancestor=ultralytics/yolov5:latest)

# DockerHub tag update
# t=ultralytics/yolov5:latest tnew=ultralytics/yolov5:v6.2 && sudo docker pull $t && sudo docker tag $t $tnew && sudo docker push $tnew

# Clean up
# sudo docker system prune -a --volumes

# Update Ubuntu drivers
# https://www.maketecheasier.com/install-nvidia-drivers-ubuntu/

# DDP test
# python -m torch.distributed.run --nproc_per_node 2 --master_port 1 train.py --epochs 3

# GCP VM from Image
# docker.io/ultralytics/yolov5:latest
